/**
 * icon 集合 最后几项是本项目中个性化的icon图标
 */
export default [
  {
    label: '阿里云图标',
    list: [
      'icon-quanxianguanli',
      'icon-yonghuguanli',
      'icon-jiaoseguanli',
      'icon-web-icon-',
      'icon-xitongguanli',
      'icon-rizhiguanli',
      'icon-navicon-zdgl',
      'icon-weibiaoti46',
      'icon-miyue',
      'icon-shouji',
      'icon-miyue',
      'icon-denglvlingpai',
      'icon-luyou',
      'icon-msnui-supervise',
      'icon-server',
      'icon-wendang',
      'icon-gtsquanjushiwufuwuGTS',
      'icon-caidanguanli',
      'icon-guanwang',
      'icon-guanwangfangwen',
      'icon-guiji',
      'icon-fensiguanli',
      'icon-gongzhonghao',
      'icon-anniu_weixincaidanlianjie',
      'icon-weixincaidan',
      'icon-xiaoxiguanli',
      'icon-zhexiantu',
      'icon-canshu',
      'icon-erji-zuhushouye',
      'icon-pay6zhifu',
      'icon-zhifuqudaoguanli',
      'icon-dingdan',
      'icon-tuikuan',
      'icon-webicon14',
      'icon-shouyintai',
      'icon-wenjianguanli',
      'icon-mysql',
      'icon-shejiyukaifa-',
      'icon-record',
      'icon-biaodanbiaoqian',
      'icon-quanxianguanli',//权限管理
      'icon-xitongguanli',//系统管理
      'icon-kucunguanli',//库存管理
      'icon-zhanghaoguanli',//账号管理
      'icon-mobanshezhi',//模板设置
      'icon-kucunliushui',//库存流水
      'icon-chukudan',//出库单
      'icon-rukudan',//入库单
      'icon-churukuliushui',//出入库流水
      'icon-kucuntaizhang',//库存台账
      'icon-xiancunliangchaxun',//现存量查询
      'icon-baobiaoguanli',//报表
    ]
  }
]
